name: test_coverage
description: Command line utility to run tests in Dart VM and collect coverage data.
version: 0.3.0
homepage: https://github.com/vitusortner/test_coverage
authors:
  - Anatoly Pulyaevskiy <anatoly.pulyaevskiy@gmail.com>
  - Vitus Ortner <vitusortner.dev@gmail.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

executables:
  test_coverage:

dependencies:
  coverage: ^0.12.4
  path: ^1.6.2
  lcov: ^5.1.0

dev_dependencies:
  test: ^1.6.1
